### PR TITLE
Environment: Merge parallel::Environment into gridpack::Environment. fixes #71

### LINKED ISSUE #71: Test application environment feature merged into master

### PR DESCRIPTION
**Pull request by abhyshr**
This change merges the contents parallel::Environment into gridpack::Environment. Any use of parallel::Environment is replaced by gridpack::Environment. The tests,
examples, and other files where parallel::Environenment are updated.

### CODE REVIEW

**Comment by bjpalmer** [comment]
Two questions
1) The math::Initialize function takes command line arguments and you are passing the command line arguments to the Environment class into the math::Initialize function. Is there anything that distinguishes arguments that are directed at the math module from arguments that are directed at the rest of the code? This may be a moot point, since I don't think we've used the command line arguments to do anything with the math module, but just curious.
2) It looks like the destructor is calling GA_Terminate but not MPI_Finalize. Any reason for this? (GA_Terminate does not call MPI_Finalize)

**Comment by wperkins** [comment]
On what platform did you test this @abhyshr?  I could not build this branch on RHEL7, because of CMake's confusing library ordering.  It built and tested fine on MacOSX. 
I would have the application environment inherit from DistributedInterface so that methods to get a communicator, and its size and rank are available directly from the environment. The communicator should be the same as the default world, but I think calling an Environment method would make clearer code.  
What happens with the config_file? Is there some reason the configuration file (if specified) cannot be opened checked, and distributed at Environment construction?

**Comment by abhyshr** [comment]
> Two questions
> 
> 1. The math::Initialize function takes command line arguments and you are passing the command line arguments to the Environment class into the math::Initialize function. Is there anything that distinguishes arguments that are directed at the math module from arguments that are directed at the rest of the code? This may be a moot point, since I don't think we've used the command line arguments to do anything with the math module, but just curious.

There is nothing to distinguish which options are applicable to the math module (PETSc) and which are general application specific options. If these general options don't use the same options tags (for .e.g -snes_type) then they will not interfere with the math options. Another option is to set prefixes for the solver (for e.g. for the dsim application, the prefix -dsim_ is set so any solver options need to be passed with the -dsim_ prefix). If you do want to really add support for distinguishing the math solver options then one way is through the prefixes, i.e., GridPACK adds specific prefixes to the solver. 


> 2. It looks like the destructor is calling GA_Terminate but not MPI_Finalize. Any reason for this? (GA_Terminate does not call MPI_Finalize)

GridPACK uses the boost::mpi::environment. My understanding is that MPI_Initialize() is called when the Environment objects gets instantiated and MPI_Finalize() is called when the destructor for boost::mpi::environment is called when the Environment object destructor is called. I've looked at the boost examples and don't see an MPI_Finalize() being called explicitly. Also, the previous implementation of Environment (in src/parallel) did not call the destructor either.

**Comment by abhyshr** [comment]
> On what platform did you test this @abhyshr? I could not build this branch on RHEL7, because of CMake's confusing library ordering. It built and tested fine on MacOSX.

I only tested this on MacOSX. What errors do you get on RHEL? I am completely unfamiliar with how CMake orders libraries and its impact on builds on different platforms.

> I would have the application environment inherit from DistributedInterface so that methods to get a communicator, and its size and rank are available directly from the environment. The communicator should be the same as the default world, but I think calling an Environment method would make clearer code.

That sounds good. I am not familiar with DistributedInterface though.

> What happens with the config_file? Is there some reason the configuration file (if specified) cannot be opened checked, and distributed at Environment construction?

I think this can be done. Will need to think about doing it correctly, especially for PETSc options.

**Comment by wperkins** [comment]
Also, Environment needs a virtual destructor, so it can be subcassed.

**Comment by wperkins** [comment]
> > On what platform did you test this @abhyshr? I could not build this branch on RHEL7, because of CMake's confusing library ordering. It built and tested fine on MacOSX.
> 
> I only tested this on MacOSX. What errors do you get on RHEL? I am completely unfamiliar with how CMake orders libraries and its impact on builds on different platforms.
>
I pushed a fix 
> > I would have the application environment inherit from DistributedInterface so that methods to get a communicator, and its size and rank are available directly from the environment. The communicator should be the same as the default world, but I think calling an Environment method would make clearer code.
> 
> That sounds good. I am not familiar with DistributedInterface though.
> 
This is completely optional.  
> > What happens with the config_file? Is there some reason the configuration file (if specified) cannot be opened checked, and distributed at Environment construction?
> 
> I think this can be done. Will need to think about doing it correctly, especially for PETSc options.

As we decided in the meeting, let's just remove references to config_file and think about it later.

**Pull request merged**
