### PR TITLE
Python interface for Dynamic simulation (full y)

### PR DESCRIPTION
**Pull request by wperkins**
This adds a Python interface for the Dynamic Simulation application.  The entire public API of the `DSFullApp` is available from Python.  Some additions to the `DSFullApp` API are added to internalize DS initialization using PF, ala the HADREC application.  Some scripts are added to emulate `dsf.x` and `dsf2.x`  and to replace some of the HADREC based Python examples.

### CODE REVIEW

**Comment by wperkins** [comment]
@bjpalmer: On this branch, I'm trying to write a Python script that does what [39bus_test_example.py](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/python/src/example/39bus_test_example.py) does using only `DSFullApp`.  My current, incomplete attempt is [39bus_test_example_dsf.py](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/python/src/example/39bus_test_example_dsf.py).  This SEGVs in `DSFullBus::getWatchedValues()` at [this point](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/src/applications/modules/dynamic_simulation_full_y/dsf_components.cpp#L2635) because the previous line calls `BaseGeneratorModel::getWatchValues()` when the HADREC script calls `GensalGenerator::getWatchValues()` at the same point.  

I think I've duplicated the way HADREC creates and runs the DS application module.  

The GDB session I used to determine this was as follows:
```
cd .../python/src/example
gdb --args /usr/bin/python 39bus_test_example_dsf.py
(gdb) run
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
gridpack::dynamic_simulation::DSFullBus::getWatchedValues (this=0x1013250, idx=0, 
    speed=0x7fffffffd420, angle=0x7fffffffd428, genP=0x7fffffffd430, genQ=0x7fffffffd438)
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/dynamic_simulation_full_y/dsf_components.cpp:2635
2635      *angle = vals[0];
(gdb) break 2634
(gdb) run
(gdb) [s a bunch of times]
gridpack::dynamic_simulation::BaseGeneratorModel::getWatchValues (this=0xb663e0, 
    vals=<error reading variable: Cannot access memory at address 0x8>)
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/dynamic_simulation_full_y/base_classes/base_generator_model.cpp:320
320         std::vector<double> &vals) {
(gdb) 
321       vals.clear();
(gdb) run 39bus_test_example.py
Thread 1 "python" hit Breakpoint 1, gridpack::dynamic_simulation::DSFullBus::getWatchedValues (
    this=0x154a2e0, idx=0, speed=0x7fffffffd4a0, angle=0x7fffffffd4a8, genP=0x7fffffffd4b0, 
    genQ=0x7fffffffd4b8)
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/dynamic_simulation_full_y/dsf_components.cpp:2634
2634      p_generators[idx]->getWatchValues(vals);
(gdb) [s a bunch of times]
gridpack::dynamic_simulation::GensalGenerator::getWatchValues (
    this=0x1555545f2f5e <std::vector<double, std::allocator<double> >::vector()+28>, 
    vals=std::vector of length -14660156900365, capacity 21 = {...})
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/dynamic_simulation_full_y/model_classes/gensal.cpp:688
688     {
(gdb) 
689       vals.clear();
```

**Comment by wperkins** [comment]
> @bjpalmer: On this branch, I'm trying to write a Python script that does what [39bus_test_example.py](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/python/src/example/39bus_test_example.py) does using only `DSFullApp`. My current, incomplete attempt is [39bus_test_example_dsf.py](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/python/src/example/39bus_test_example_dsf.py). This SEGVs in `DSFullBus::getWatchedValues()` at [this point](https://github.com/GridOPTICS/GridPACK/blob/b3a28492195a81f3156f23125fad00c15c0e240f/src/applications/modules/dynamic_simulation_full_y/dsf_components.cpp#L2635) because the previous line calls `BaseGeneratorModel::getWatchValues()` when the HADREC script calls `GensalGenerator::getWatchValues()` at the same point.

I think I found the problem.  I neglected to provide the same index to `DSFullApp::readGenerators()` that the HADREC example does.   I'll continue.

**Comment by wperkins** [comment]
This is ready for review.

@yliu250, you probably have the most experience with the Python interface. Can you check out the two Python scripts that I wrote/adapted for the 39-bus: `python/src/example/39bus_test_example_dsf.py` and `python/src/example/39bus_test_example_dsf.py`.  Let me know if there are features that the HADREC Python interface has that the DS interface needs.

**Comment by yliu250** [comment]
@wperkins I reviewed the python/src/example/39bus_test_example_dsf.py example. It looks good to me. What we implemented in HADREC is mostly handled here. One thing we can probably improve is to output the header list along with the values when we use ds_app.getObservationLists() or ds_app.getObservations_withBusFreq(). Or we can develop a separate function such as ds_app.getObservationListsHeaders() to output the header strings according to the output channels. Bascally we can wrap the below in a function. This is not an important or urgent update though.

csvhead = []
csvhead.append('time')
for itmp in range(len(obs_genBus)):
    csvhead.append('gen-spd-%d-%s'%(obs_genBus[itmp], obs_genIDs[itmp]))
for itmp in range(len(obs_genBus)):
    csvhead.append('gen-ang-%d-%s'%(obs_genBus[itmp], obs_genIDs[itmp]))
for itmp in range(len(obs_genBus)):
    csvhead.append('gen-P-%d-%s'%(obs_genBus[itmp], obs_genIDs[itmp]))
for itmp in range(len(obs_genBus)):
    csvhead.append('gen-Q-%d-%s'%(obs_genBus[itmp], obs_genIDs[itmp]))
for itmp in range(len(obs_busIDs)):
    csvhead.append('bus-%d-v'%(obs_busIDs[itmp]))
for itmp in range(len(obs_busIDs)):
    csvhead.append('bus-%d-ang'%(obs_busIDs[itmp]))

**Review by abhyshr — APPROVED** [review]

**Pull request merged**
