### PR TITLE
Add Rocky build automation via PNNL GitLab

### PR DESCRIPTION
**Pull request by jacksavage**
- updates `install_gridpack_deps.sh` and `install_gridpack.sh`.
- adds definition for a gitlab build pipeline via `.gitlab-ci.yml`. this contains jobs that install gridpack and run gridpack tests. there is a third job that builds a container image used as the environment for those jobs.
- adds dockerfile, defining the container image.

### CODE REVIEW

**Comment by wperkins** [comment]
I think #164 will be required to make this work.  We may also need to consider #174.

**Comment by wperkins** [comment]
> I think #164 will be required to make this work. 

I see you are already using #164.

**Comment by wperkins** [comment]
Consider showing test output when it fails
```
ctest --output-on-failure
```

**Comment by wperkins** [comment]
@jacksavage, I think if you rebase from develop now, the test suite should pass.  You may need to build PETSc with MUMPS instead of SuperLU_dist, but you should try it as it is now.

**Comment by wperkins** [comment]
> You may need to build PETSc with MUMPS instead of SuperLU_dist

@jacksavage, to build PETSc with MUMPS, make this change:
```
diff --git a/install_gridpack_deps.sh b/install_gridpack_deps.sh
index a9a1950c..46f4e997 100755
--- a/install_gridpack_deps.sh
+++ b/install_gridpack_deps.sh
@@ -117,7 +117,7 @@ function install_petsc {
   # install
   echo "Configuring PETSc"
   ./configure \
-    --download-superlu_dist \
+    --download-mumps \
     --download-metis \
     --download-parmetis \
     --download-suitesparse \
```

**Comment by jacksavage** [comment]
@abhyshr and @wperkins, I was able to get the container to build properly after removing `--download-f2cblaslapack=1` from the PETSc config.

now, I have an error installing the python wrapper which states the `mpi4py` package is missing ([link](https://devops.pnnl.gov/gridpack-code/GridPACK/-/jobs/161354#L1841)). I see that CMake checks for this ([link](https://github.com/GridOPTICS/GridPACK/blob/6a576eee10ad926792d9c81aa79e701a17f96a26/python/CMakeLists.txt#L46-L57)). is this actually a dependency for building the package? looks like it was temporarily a part of `setup_requires` ([link](https://github.com/GridOPTICS/GridPACK/pull/119/commits/c14d1252be9b78a6f0435ceda2a56b8b0374b9ac)), of which I'm not familiar. setuptools docs say this is deprecated ([link](https://setuptools.pypa.io/en/latest/references/keywords.html)), pointing to PEP 518 which recommends a `pyproject.toml` ([link](https://peps.python.org/pep-0518/#file-format)). is that something we need to add and install dependencies from before building the package ([link](https://github.com/GridOPTICS/GridPACK/blob/6a576eee10ad926792d9c81aa79e701a17f96a26/install_gridpack.sh#L96))?

#119 is possibly of interest

**Comment by abhyshr** [comment]
Jack,
   Can you install mpi4py (pip install mpi4py --user) independently and try again?

Shri

From: Jack Savage ***@***.***>
Date: Friday, January 19, 2024 at 6:07 PM
To: GridOPTICS/GridPACK ***@***.***>
Cc: Abhyankar, Shrirang G ***@***.***>, Mention ***@***.***>
Subject: Re: [GridOPTICS/GridPACK] Add build automation via PNNL GitLab (PR #173)
Check twice before you click! This email originated from outside PNNL.


@abhyshr<https://github.com/abhyshr> and @wperkins<https://github.com/wperkins>, I was able to get the container to build properly after removing --download-f2cblaslapack=1 from the PETSc config.

now, I have an error installing the python wrapper which states the mpi4py package is missing (link<https://devops.pnnl.gov/gridpack-code/GridPACK/-/jobs/161354#L1841>). I see that CMake checks for this (link<https://github.com/GridOPTICS/GridPACK/blob/6a576eee10ad926792d9c81aa79e701a17f96a26/python/CMakeLists.txt#L46-L57>). is this actually a dependency for building the package? looks like it was temporarily a part of setup_requires (link<https://github.com/GridOPTICS/GridPACK/pull/119/commits/c14d1252be9b78a6f0435ceda2a56b8b0374b9ac>), of which I'm not familiar. setuptools docs say this is deprecated (link<https://setuptools.pypa.io/en/latest/references/keywords.html>), pointing to PEP 518 which recommends a pyproject.toml (link<https://peps.python.org/pep-0518/#file-format>). is that something we need to add and install dependencies from before building the package (link<https://github.com/GridOPTICS/GridPACK/blob/6a576eee10ad926792d9c81aa79e701a17f96a26/install_gridpack.sh#L96>)?

#119<https://github.com/GridOPTICS/GridPACK/pull/119> is possibly of interest

**Comment by wperkins** [comment]
> Can you install mpi4py (pip install mpi4py --user) independently and try again?

@jacksavage, I recommend installing the system package, which should be `python3-mpi4py` on Ubuntu, over pip.  pip often leads to package versions incompatible with the system packages, for me anyway.

**Comment by abhyshr** [comment]
@jacksavage : What is the status of this work?

**Comment by jacksavage** [comment]
> @jacksavage : What is the status of this work?

hi @abhyshr, I was able to get the ubuntu build working and the tests are able to run (as of 31d1fb274d43a75264f408cc3fe853f9a827cc6e). a few tests are failing, maybe the ones that are expected to.

right now, I'm trying to get the rocky linux (RHEL-like) build to work. I ran into an issue with the PNNL proxy and needed to request a url for the package repo list be unblocked. now I'm troubleshooting an issue with the Global Arrays install - "Could not determine the C compiler wrapped by MPI".

**Comment by jacksavage** [comment]
@wperkins, thanks for the help in regard to loading the module for `mpi4py`. on the rocky linux build, I'm now running into in error with the gridpack installation when running 

```
cmake \
  -D GA_DIR:STRING=/gridpack-dependencies/ga/install_for_gridpack \
  -D BOOST_ROOT:STRING=/gridpack-dependencies/boost/install_for_gridpack \
  -D Boost_DIR:STRING=/gridpack-dependencies/boost/install_for_gridpack/lib/cmake/Boost \
  -D Boost_LIBRARIES:STRING=/gridpack-dependencies/boost/install_for_gridpack/lib \
  -D Boost_INCLUDE_DIRS:STRING=/gridpack-dependencies/boost/install_for_gridpack/include \
  -D PETSC_DIR:PATH=/gridpack-dependencies/petsc/install_for_gridpack \
  -D MPI_CXX_COMPILER:STRING=mpicxx \
  -D MPI_C_COMPILER:STRING=mpicc \
  -D MPIEXEC:STRING=mpiexec \
  -D GRIDPACK_TEST_TIMEOUT:STRING=30 \
  -D CMAKE_INSTALL_PREFIX:PATH=/build/src/install \
  -D CMAKE_BUILD_TYPE:STRING=Debug \
  -D BUILD_SHARED_LIBS=YES \
  -D Boost_NO_SYSTEM_PATHS:BOOL=TRUE \
  -D Boost_NO_BOOST_CMAKE:BOOL=TRUE \
  -D MPIEXEC_MAX_NUMPROCS:STRING=2 \
  ..
```

the error is

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: mpi) (found suitable version "1.78.0",
  minimum required is "1.53")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  CMakeLists.txt:270 (find_package)
```

any ideas about this?

**Comment by wperkins** [comment]
> [...]
> ```
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Boost (missing: mpi) (found suitable version "1.78.0",
>   minimum required is "1.53")
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
>   CMakeLists.txt:270 (find_package)
> ```
> 
> any ideas about this?

Are you using the system boost package? If so, did you install  the `boost-openmpi` package (https://rockylinux.pkgs.org/8/rockylinux-powertools-x86_64/boost-openmpi-1.66.0-13.el8.x86_64.rpm.html)? 

If you are building Boost from source, do not install any system Boost packages, or add `-D Boost_NO_SYSTEM_PATHS=TRUE` to GridPACK configuration.

**Comment by wperkins** [comment]
> hi @abhyshr, I was able to get the ubuntu build working and the tests are able to run (as of [31d1fb2](https://github.com/GridOPTICS/GridPACK/commit/31d1fb274d43a75264f408cc3fe853f9a827cc6e)). a few tests are failing, maybe the ones that are expected to.

@jacksavage, it looks like the tests that fail (wind DSA) are just timing out.  You can increase the time out time with the GridPACK configuration option `-D GRIDPACK_TEST_TIMEOUT` (in seconds). Or, if they take more time that you can stand, you might just exclude them (`ctest -E 'wind.*dsa'`). 

Just out of curiosity, are we going to keep hiding the CI test results on PNNL's Gitlab, or is there a plan to expose the results/logs on Github?

**Comment by jacksavage** [comment]
@wperkins, looks like I was able to get all tests passing with a 120 second timeout. thanks.

in regard to exposing test results to GitHub, I haven't come across a simple way to do that. the only thing that seems to be supported by the [GitLab integration](https://docs.gitlab.com/ee/user/project/integrations/github.html) is reporting the build status and providing a link to results. did we choose to build on PNNL GitLab for the eventual access to HPC? if not, I suppose moving the build to GitHub would be worth exploring - if we want results here and public.

**Comment by jacksavage** [comment]
Closing this PR because #195 contains everything needed to continue work adding Rocky Linux support.

**Pull request closed without merging**
