### PR TITLE
Add methods to change dynamic simulation state

### PR DESCRIPTION
**Pull request by bjpalmer**
Creating merge request so I can compare current branch with develop

### CODE REVIEW

**Review by wperkins — COMMENTED** [review]
Why is it necessary to override `SetState()` in the child classes when it has exactly the same implementation as the base classes: `BaseExciterModel`, `BaseGeneratorModel`, and `BaseGovernorModel`.  The child class should only implement a virtual member if a different implementation is required. 

`SetState()` is implemented identically in those base classes.  Are there other commonalities in those base classes that might justify a common ancestor or interface class?

**Comment by bjpalmer** [comment]
The idea was to just create stubs that would. be filled in with the actual implementation later. The base class implementation just guarantees that things compile okay but if you actually want something to happen, the stubs in the derived classes need to be filled in.

**Comment by wperkins** [comment]
> The idea was to just create stubs that would. be filled in with the actual implementation later. The base class implementation just guarantees that things compile okay but if you actually want something to happen, the stubs in the derived classes need to be filled in.

IMO, adding a virtual member to the base class is enough to create a "stub".  If someone wants to change the default `SetState()` behavior in the base class, all child classes will have to be modified to reflect that.  If it's really necessary to have subclass implementations that are identical to the base class, they should be implemented by calling the base method. For example: 
```c++
bool gridpack::dynamic_simulation::Exdc1Model::setState(std::string name,
    double value)
{
  return gridpack::dynamic_simulation::BaseExciterModel::setState(name, value);
}
```
which is exactly what happens if the subclass does not override the base class method.

**Comment by abhyshr** [comment]
I agree. There is no need to declare the method `virtual` in the child class.

**Comment by bjpalmer** [comment]
Just to be clear, none of the child classes are declaring setState to be virtual. The only reason I'm explicitly including the stubs in the classes is so that there will already be a function defined for anyone that wants to fill in the details. It isn't necessary to include the stubs, but it will make it easier implement these functions when someone gets around to doing it.

**Comment by abhyshr** [comment]
@wperkins: Can you add a python wrapper for the `setState` method?
 
@bjpalmer : Is there a `setState` method added to the hadrec application? This is what will be eventually called by the python wrapper.

**Comment by bjpalmer** [comment]
I didn't add set state to the hadrec model, but I assume it would be straightforward.

**Comment by wperkins** [comment]
> @wperkins: Can you add a python wrapper for the `setState` method?

Yes. 

> I didn't add set state to the hadrec model, but I assume it would be straightforward.

I can do this, if you want.

**Comment by bjpalmer** [comment]
I added a getState function to the dynamic simulation modules and setState and getState functions to the HADREC module. Everything compiles. I will try a quick test with setState to see if it actually works.

Bill, if you want to add the python wrappers for setState and getState, you should be good to go.

**Comment by abhyshr** [comment]
@yliu250: Looks like this functionality is in place. Can you test it by adding setState and getState calls to the python dynamics simulation application?

**Comment by bjpalmer** [comment]
Don't do anything just yet. I'm doing some simple tests on the kundar 2-area network and things look pretty buggy. I'll let you know when they are fixed.

**Comment by bjpalmer** [comment]
Okay, the code isn't so buggy but my ability to read my own documentation leaves a bit to be desired. I ran some quick tests and the setState/getState functions seem okay, at least for generators. I also made a few changes that should make them more robust.

Two tangential observations:
1) the variable corresponding to ANGLE in GENROU doesn't look like it is getting initialized properly. The initial value before resetting it is 1.45996e-319
2) the kundar 2-area simulation is not exiting cleanly, even if I make no changes. It does appear to running the simulation though.

**Comment by abhyshr** [comment]
> Okay, the code isn't so buggy but my ability to read my own documentation leaves a bit to be desired. I ran some quick tests and the setState/getState functions seem okay, at least for generators. I also made a few changes that should make them more robust.
> 
> Two tangential observations:
> 
> 1. the variable corresponding to ANGLE in GENROU doesn't look like it is getting initialized properly. The initial value before resetting it is 1.45996e-319
The getState() function needs to be called _after_ the initialization is done, i.e. after ds_app.solvePreInitialize() in ds_main.cpp.
> 2. the kundar 2-area simulation is not exiting cleanly, even if I make no changes. It does appear to running the simulation though.
Yes, it does exit uncleanly for me as well sometimes. Likely there is some messy stuff in freeiing/deallocation that is causing it.

**Comment by abhyshr** [comment]
@yliu250 : What is the status of testing this feature? We need to get this functionality to UTK as soon as possible to allow them to start working with it.

**Comment by yliu250** [comment]
@abhyshr: I tested the getState and setState functions on IEEE 39 bus system and printed the results. They work as expected. I think they are ready for use now. I will further test it on WECC 240 bus system tomorrow.

**Comment by abhyshr** [comment]
Merged to develop. Thanks @bjpalmer @wperkins @yliu250

**Pull request merged**
