### PR TITLE
Updates GridPACK to be in sync with PETSc master.

### PR DESCRIPTION
**Pull request by abhyshr**
This change updates GridPACK to be in synch with PETSc master.

### CODE REVIEW

**Comment by wperkins** [comment]
It appears that these changes do not have any backward compatibility.  What is the minimum PETSc version supported?  I think we should try to maintain compatibility with all 3.x versions, but at least back to 3.4.

**Comment by abhyshr** [comment]
Is there a strong reason to maintain backward compatibility? 

If there is one, do you suggest to sprinkle #ifdefs inside src/math/petsc to handle different PETSc versions?

#if PETSC_VERSION_LT(3.7)
  PETSc code compatible with versions less than 3.7
#elseif PETSC_VERSION_LT(3.xx)
   PETSc code compatible with versions less than 3.8
#else 
   petsc-master compatible function call.
   
 petsc-3.4 was released in 2013. I am not sure of  keeping compatability with a six year old petsc.

**Comment by bjpalmer** [comment]
Is it that big a deal to maintain backward compatibility? The existing code is already doing it and it seems like it shouldn't be hard to keep that up. I admit that 6 years is a long time ago, but people keep using ancient stuff for all sorts of reasons. Just look at some of the defaults on constance.

**Comment by abhyshr** [comment]
There are not many changes in the PETSc API since 3.7. So, keeping backward compatibility would not be a big code change in GridPACK. We can even keep compatibility with 6-year old 3.4 as I think that would not be too much of a change either. But, I think it would be good to keep GridPACK master updated with PETSc master and support perhaps max. 2-year old PETSc compatibility. Any previous PETSc versions I assume will be supported by GridPACK releases. Thoughts?

**Comment by wperkins** [comment]
The PETSc version in Ubuntu 16 LTS is 3.6.2.  Ubuntu 16 is supported until April 2021.  We need to to be compatible that at least. If these changes work w/ PETSc 3.6.2, then they are fine w/ me.

**Comment by abhyshr** [comment]
I don't think these changes will work with PETSc 3.6.2. There were some API changes made with 3.10 and 3.11 that result in this incompatibility. Let us discard this pull request. I'll create another one that has compatibility from 3.6.2 through 3.11.

**Comment by abhyshr** [comment]
PETSc 3.16 compatibility is implemented in the develop branch.

**Pull request closed without merging**
