### PR TITLE
forked and changed

### PR DESCRIPTION
**Pull request by arunveeramany**

### CODE REVIEW

**Comment by wperkins** [comment]
This looks good to me and should be merged, but @bjpalmer should have the final say.

**Comment by bjpalmer** [comment]
It looks like you moved test_serial_io so that it only gets called if you are building with GOSS in the CMakeLists.txt file. Could you add an "else()" clause so that it still gets built even if you are not building with GOSS?

**Comment by bjpalmer** [comment]
Looks good.

**Comment by bjpalmer** [comment]
Forgot to merge this pull request before closing it.

**Pull request merged**
