### PR TITLE
Initial implementation of DAE Solver events

### PR DESCRIPTION
**Pull request by wperkins**
I have an initial implementation of [events for the DAESolver](#68).  I consider this sort of a rough draft and it does not interfere with existing capabilities or code. So, I think it's OK to bring into the main repository.  I hope it's enough to make sure I'm headed towards a  usable implementation at the application/module level.  

I have coded the [PETSc bouncing ball example ](https://www.mcs.anl.gov/petsc/petsc-current/src/ts/examples/tutorials/ex40.c.html) in [bouncing_ball_test.cpp](wperkins/GridPACK/blob/master/src/math/test/bouncing_ball_test.cpp).  This is a serial example, that provides a simple example of GridPACK DAE event usage.   

I'm working on coding an example based on the [PETSc 9-bus example](https://gitlab.com/petsc/petsc/blob/master/src/ts/examples/tutorials/power_grid/stability_9bus/ex9bus.c), but it could be a little while before I have that done.

### CODE REVIEW

**Comment by abhyshr** [comment]
@wperkins : Thanks. This looks good to me. For my understanding, let me know if the following is correct.
1. `DAEEventT` is the object for handling individual event(s). There can be one or more events for DAEEventT.
1. In `const std::vector<T>& values(const double& t, T *state)`, the state are the states for that particular event. For instance, if the event is at a bus then it will `state` will be array of bus state variables?
1. `DAEEventManagerT` manages one or more `DAEEventT` and acts an interface between the PETSc event interface and the application.

**Comment by wperkins** [comment]
@abhyshr 
>     1. `DAEEventT` is the object for handling individual event(s). There can be one or more events for DAEEventT.

Yes.  There can be an arbitrary number, and they can be specialized in any way. 

>     2. In `const std::vector<T>& values(const double& t, T *state)`, the state are the states for that particular event. For instance, if the event is at a bus then it will `state` will be array of bus state variables?

Yes. The DAEEventT<> is expected to know the local offset into the state vector. 

>     3. `DAEEventManagerT` manages one or more `DAEEventT` and acts an interface between the PETSc event interface and the application.

Yes. It to can be specialized if necessary. 

Thanks for looking it over.

**Comment by bjpalmer** [comment]
When you say DAEEvent<> is suppose to know the offset into the state vector, does that mean that the event internally is expected to store a range of values that correspond to the values it will use to do its calculations? Assuming that events are associated with individual network elements (i.e. buses or branches) is this going to be a problem if the event depends on values of other network elements? In that case, the DAEEvent<> might depend on a non-contiguous set of values in the state vector.

If this is the case, might it not be better to push the values of the state vector back to the buses and branches, calculate whatever values need to be calculated and then make these available to the event? We could add another to layer between the event handlers and the user to make this relatively transparent (if we need to do it).

**Comment by wperkins** [comment]
@bjpalmer 

> When you say DAEEvent<> is suppose to know the offset into the state vector, does that mean that the event internally is expected to store a range of values that correspond to the values it will use to do its calculations? Assuming that events are associated with individual network elements (i.e. buses or branches) is this going to be a problem if the event depends on values of other network elements? In that case, the DAEEvent<> might depend on a non-contiguous set of values in the state vector.

There is nothing to limit an event to a particular part of the state vector.  If you want the event to see the entire local state vector, it can.  There is no requirement that the Event use the state vector at all.  

There is no requirement that events be associated with  individual network components, but that would be the simplest. An event could be generated by the network, perhaps, if it  involves multiple components.

I would expect that the mapper would be involved in setting the state vector offset for a particular (single component based) event. 
 
> If this is the case, might it not be better to push the values of the state vector back to the buses and branches, calculate whatever values need to be calculated and then make these available to the event? We could add another to layer between the event handlers and the user to make this relatively transparent (if we need to do it).

If the entire network needs to be involved in an event, then the event manager can be specialized to put the state back on the network.  However, if an event is localized to a single component, why not let that component handle the event without involving the entire network? 

Presumably, the Event and Event Manager classes will be subclassed and specialized to interact with specific component types, and the specific mapper, depending on the analysis and/or network type.

**Pull request merged**
